### ISSUE TITLE
qemu w/ 'host/hvf' crashes in version 0.8

### ISSUE THREAD

**Issue by bpint** [beringresearch/macpine#63] opened 2023-01-09 23:42 UTC
When I upgraded macpine to 0.8, it frequently crashed with error 'vmx_write_mem: mmu_gva_to_gpa failed'.

I googled a little, and found it might related to wrong cpu type specified. [QEMU .qcow2 mmu_gva_to_gpa crash in Mac OS X](https://stackoverflow.com/questions/60231203/qemu-qcow2-mmu-gva-to-gpa-crash-in-mac-os-x)

Is there any workaround for v0.8, that I can change the 'cpu host' parameter in qemu command line?

Would you consider change '-cpu host' to '-cpu base', or autodetect the right cpu type?

**Comment by idroz** [comment] 2023-01-10 05:48
Thanks - does this happen at launch or when you're doing something inside the VM?

**Comment by bpint** [comment] 2023-01-10 09:42
Thanks for the response.

1. Your host CPU arch

```console
$ sysctl -a | grep machdep.cpu.brand_string
machdep.cpu.brand_string: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
```
2. macpine CPU instance you're launching (aarch64 vs x86_64)
3. resources you're allocated to the vm - default, vs ram/cores

```console
$ cat ~/.macpine/ubuntu/config.yaml
alias: ubuntu
image: ubuntu_22.04.1_lxd-x86_64.qcow2
arch: x86_64
cpu: "6"
memory: "12288"
disk: 512G
mount: ""
port: 8443,6443
sshport: "65522"
sshuser: root
sshpassword: root
macaddress: 56:fd:fc:07:21:82
location: /Users/bpint/.macpine/ubuntu
```

**I am sorry that it is not an official image. I cooked up an ubuntu image with qemu (host qemu64) from live cd installation. It worked fine in macpine 0.7.**

4. preferably a small set of commands that would reproduce the error and help test any fixes

- I started the instance with `alpine start ubuntu`, and I ran `apt upgrade`. It happened to upgrade the kernel. I think it crashed during the generating process of initrd. I finally succeeded in upgrading the kernel by switching back to host qemu64 (macpine 0.7).

- I had lxd inside the instance. When I run `lxc start sth`, the instance also crashed with `vmx_write_mem: mmu_gva_to_gpa` error.

**Comment by bpint** [comment] 2023-01-10 10:01
Great. By the way, thanks for the awesome software. I think it is more lightweight, flexible, friendly to developers than multipass/docker-desktop.

**Comment by bpint** [comment] 2023-01-10 14:10
FYI, as a workaround, I built a version from the macpine source. I changed "host" to "host,-pdpe1gb" according to the solution previous mentioned [QEMU .qcow2 mmu_gva_to_gpa crash in Mac OS X](https://stackoverflow.com/questions/60231203/qemu-qcow2-mmu-gva-to-gpa-crash-in-mac-os-x).

The built version works just fine for me, till now. The VM survived lxd and 3-node k8s in it.

**Comment by idroz** [comment] 2023-01-10 14:23
I was thinking along similar lines but have no way of testing.

Did you change https://github.com/beringresearch/macpine/blob/1d567b5a40b6ef67778e4be0eefffecba3e1b1c4/qemu/ops.go#L255

to `host,-pdpe1gb` ?

If that's the case I can make a pull request.

If not, feel free to make a pull request and I'll test to make sure it works on m1 and will merge

**Comment by bpint** [comment] 2023-01-10 14:49
Yes. It was exactly I did. "host,-pdpe1gb" is suppose to disable 1g huge page support.
It might because of either macos does not support 1g huge page, or my CPU does not support it.  I am not sure.

**Comment by idroz** [comment] 2023-01-10 14:55
Cool - I've added that in #64 and tested on m1 - works fine. I'm presuming this solves your issue as well?

I merged this change into master, but if you could confirm it works well, I'll make a minor release.

I think the issue is intel hosts and huge page support. M1s seem to work around that somehow.

**Comment by bpint** [comment] 2023-01-11 00:54
Yeah! I have used it with my old instance for a couple of hours and there were no crashes. I even get the impression the VM is somehow faster than before.

**Comment by idroz** [comment] 2023-01-11 10:12
Nice - thanks for catching this issue. I made a new release (https://github.com/beringresearch/macpine/releases/tag/v0.9) that incorporates the fix

**Closed by idroz** 2023-01-11 10:12 UTC
