### ISSUE TITLE
Cannot start VM with ssh set to non-root user

### ISSUE THREAD

**Issue by maxzinkus** [beringresearch/macpine#67] opened 2023-02-26 06:50 UTC
If you change the `sshuser` to anything but `root` (even with a correct password for that non-root user), alpine linux fails to boot with the repeated error message:

```hwclock: can't open '/dev/misc/rtc': No such file or directory```

I assume something in the boot process is using ssh to log in and configure something, but perhaps doesn't have access to the real-time clock file causing this failure.

**Comment by maxzinkus** [comment] 2023-02-26 19:40
I've confirmed the issue. [`qemu/ops.go:333`](https://github.com/beringresearch/macpine/blob/32ac81c36caf869582b9ee5d2aa92e272007d475/qemu/ops.go#L333) tries to `c.Exec("hwclock -s")` which cannot be done by a non-root user. 

* Adding `doas` would be a hack requiring the `ssh user` to have `nopasswd` root access
* Configuring `hwclock` to be a `setuid` binary is a slightly more robust solution, but may have unintended consequences and requires patching the base image
* Documenting that `sshuser` must be `root` is the "hands-in-the-air" wontfix solution

It may be the case that syncing `hwclock` is not vital to system operation. If that's the case, the step could be skipped with a printed warning on system boot. Prompt the user to run `hwclock -s` as root as soon as possible.

Further, if mount configurations are provided, [`qemu/ops.go:345`](https://github.com/beringresearch/macpine/blob/32ac81c36caf869582b9ee5d2aa92e272007d475/qemu/ops.go#L345) calls `c.Exec("DIR=$(eval echo \"~$USER\");mkdir -p $DIR/mnt/; chmod 777 $DIR/mnt; mount -t 9p -o trans=virtio host0 $DIR/mnt/ -oversion=9p2000.L,msize=104857600")`. This command operates relative the the user's home directory and therefore may not fail if run as a non-root user, however, this should be tested in resolving the overall issue.

**Comment by maxzinkus** [comment] 2023-02-26 19:44
@idroz if you have a minute, I'd love your guidance here. I can open a PR if any of the solutions look good but it's a higher-impact change.

**Comment by idroz** [comment] 2023-02-26 19:54
Thanks very much for spotting this. I was able to reproduce.

`hwclock` is relatively important due to https://github.com/canonical/multipass/issues/2430.

If it's committed, packages that require certificates (e.g. LXD) will stop working as expecting due to VM being "in the future" or "in the most"  vs. some server setting.

A possibility here is to simply add a check `if c.SSHUser == "root"` before executing `hwclock`.

I need to test if this solution will work with mounts as described above.

Does this sound reasonable @maxzinkus ?

**Comment by maxzinkus** [comment] 2023-02-26 20:08
So if the user changes the `SSHUser`, their clock will not be synced, leading to that same certificate issue. On one hand, you could argue that if the user gets a clock sync error it's their job to call `hwclock -s` as root. On the other hand, this solution will _create_ that situation more often than not..

The issue at canonical has been closed with a workaround hack. Really, it'd make more sense for an `openrc` runlevel to call `hwclock -s` when the system starts/resumes, or for the issue to be fixed upstream with a `qemu` configuration/startup hook.

All said, I think it makes the most sense to do the following:
* Add a `root=false` function option to `Exec` (i.e. default false)
* If `root=true`, `Exec` should ssh as root to perform the command
* Require the user to add `rootpassword` to `config.yaml` IF they change the root password (default to `root` for `rootpassword` inside `Exec`)
* use `c.Exec("hwclock -s", root=true)` in `Start`

That way, everything will work as intended by default, with no additional user configuration. Let's add a documentation note in README that if they change the root password, it must be added to `config.yaml`. I will open a separate PR for more security surrounding `config.yaml` allowing credentials to be read out of the environment or the keychain.

**Comment by maxzinkus** [comment] 2023-02-26 20:10
This also leaves room for future commands which must be run as root. The internal use of `Exec("...", root=true)` can then be used any time we know a command needs privileges, regardless of the `SSHUser` configuration.

**Comment by maxzinkus** [comment] 2023-02-26 20:11
@idroz I can open this PR if that approach sounds good to you. I'm loving using the project btw- the VMs are _blazing fast_ on my M1 Max <3

**Comment by idroz** [comment] 2023-02-26 20:14
Cool @maxzinkus - I like the `Exec("...", root=true)` approach. Let's go for that.

Just a note as tested, https://github.com/beringresearch/macpine/blob/32ac81c36caf869582b9ee5d2aa92e272007d475/qemu/ops.go#L345

This will require `root=true` as `mount` can only be executed as root.

**Comment by maxzinkus** [comment] 2023-02-26 20:18
Awesome, sounds great -- I'll open the PR shortly.

In general on unix, `mount` _can_ be run by non-root users if they have `rwx` (maybe only `rw`?) on the dev special "file" they are mounting and ownership of the destination directory. However, I bet that `qemu` is exposing the `virtio` device as a root-owned "file", and therefore a non-root user can't `mount` it. So I'll add `root=true` to the mount command as well. Their data will always end up in `/root/mnt` so they'll have to access it as root, but that's fine.

**Comment by maxzinkus** [comment] 2023-02-26 20:18
Feel free to assign this issue to me :)

**Comment by idroz** [comment] 2023-02-26 20:21
Thanks @maxzinkus - assigned :) - looking forward to testing it out.

I think makes sense that mount is only available as root since it was mounted at launch by root. I think I will add a `mount` subcommand as right now mount only happens at launch of a new vm.

**Closed** 2023-02-28 19:21 UTC
